### ISSUE TITLE
Don't working animation.

### ISSUE THREAD

**Issue by Klesaak** [unldenis/Hologram-Lib#11]
Animation CIRCLE does not working. Block is not rotate, but that still in air

**Comment by unldenis** [comment]
What version does the mc server run?

**Comment by Klesaak** [comment]
> 

Server run is paper 1_8_R3

**Comment by unldenis** [comment]
The library is available from 1.8 8. 
I seem to have already encountered this problem for the 1.8.8, probably the packet has something wrong.

**Comment by unldenis** [comment]
Fixed since 1.2.8.
