### ISSUE TITLE
Ability to hide the hologram from all players

### ISSUE THREAD

**Issue by AerWyn81** [unldenis/Hologram-Lib#14]
Hello, great resource!

Is there any way to add a method in Hologram to choose to hide or show the hologram to all players by default (ex: `hologram.setVisibleByDefault(false)`) ? 

In my case, I want to create a hologram, hide it from all players (and those who will join later) and under certain conditions display it to some players.

Is this kind of functionality implementable?

Thanks :)

**Comment by unldenis** [comment]
Thanks to the <a href="https://github.com/unldenis/Hologram-Lib/commit/45bffb62c6b704558e9de967b4a67692f8d3f6d7">latest</a> commit you can do it!
When a player joins the server you simply add him to the excluded players.
So to show only certain players just remove them from the excluded players!

You can see a simple example updated on readMe.

**Comment by AerWyn81** [comment]
Hi,

Thanks for the quick response and addition!

So if I want to hide the hologram from all players, when I create my hologram, I have to store the hologram list and get the list for each connected players and then add them to the "excludedPlayers" for each hologram? 
Then when others players will join, I have to add it to excludePlayers? 

I find this heavy....
Wouldn't it have been easier if the api had handled this behavior? 
To have the option on the hologram by default according to a method directly on the hologram as on the example of my first message and to manage the show/hide afterwards? 

If I had some freetime I would have made a PR to try but I'm a bit busy at the moment. 
If it's not possible, I'll deal with it no worries! 

Thank you again for your rapidity :)

**Comment by AerWyn81** [comment]
Hi, my previous comment was not necessary sorry, by taking it back much later, I could do what I wanted, perfect!

I close this issue.
