### ISSUE TITLE
Issue with click and empty lines

### ISSUE THREAD

**Issue by AerWyn81** [unldenis/Hologram-Lib#15]
Hi,

Is it possible to hide those unsightly lines when there is no content?
https://prnt.sc/Nj7_R5Gl2_8A

I have a hologram in my head, I can't click on the head, is this fixable?
https://prnt.sc/5WRv9FK6WwCS

Best regards.

**Comment by AerWyn81** [comment]
Hi, little up, is a fix or workaround possible?

Thanks!

**Comment by unldenis** [comment]
Hello.
> Is it possible to hide those unsightly lines when there is no content?
> https://prnt.sc/Nj7_R5Gl2_8A

It could be an idea for the next version.



> I have a hologram in my head, I can't click on the head, is this fixable?
> https://prnt.sc/5WRv9FK6WwCS

It could be fixable, perhaps with a mini armorstand ...

**Comment by AerWyn81** [comment]
Hi, thanks for your reply.

Any ETA when the next version will be released? :)

Is there any way from the API to use a mini armorstand?

**Comment by unldenis** [comment]
> Any ETA when the next version will be released? :)

Today I had in mind to do it.

> Is there any way from the API to use a mini armorstand?

In [theory](https://wiki.vg/Entity_metadata#Armor_Stand) it is enough to give the bytemask `0x01` to the spawn. Which I have been planning to add for a while.

**Comment by unldenis** [comment]
Since [1.4.0](https://github.com/unldenis/Hologram-Lib/releases/tag/1.4.0) TextLines with no content are [hidden](https://github.com/unldenis/Hologram-Lib/blob/d5fa335ec6eb093043c0f51f31bf1a79b0d932c7/src/main/java/com/github/unldenis/hologram/TextLine.java#L51), for hitboxes I can't do more than make the armorstand small.

**Comment by AerWyn81** [comment]
Thanks! I tried the latest version of the API and it seems to fix both issues!

But it seems that there is a side effect: https://prnt.sc/bAgjjJWOKELO
The color of the writing in the hologram is shaded
I placed the hologram at +0.5 height from the head
