### ISSUE TITLE
Getting a hologram

### ISSUE THREAD

**Issue by Enoughsdv** [unldenis/Hologram-Lib#21]
How can I get some hologram, I was looking at the library code and I can't find any method to get this unless I modify it.

ex:
```java
public void moveHologram(Player player, ???? ???) {
    hologramPool.getHologram(???).teleport(player.getLocation());
}
```

**Comment by LowScarlet** [comment]
same issue here, you got it?

**Comment by Enoughsdv** [comment]
Oh yes, I saw that with the latest update you can do `HologramPool#getHolograms`, in order to get the holograms I just got the location of each hologram by comparing it to the ones in my config file that I wanted to get.

That is a possible solution, I think there are several, for example getting the name (uuid) of the hologram and delete it from the `HologramPool`.
