### ISSUE TITLE
FieldAccessException

### ISSUE THREAD

**Issue by zxcemelya** [unldenis/Hologram-Lib#38]
![image](https://github.com/unldenis/Hologram-Lib/assets/110854715/5ff15a14-3eb9-4ed8-ad5b-eb316736e7fa)

i just copy code in example

**Comment by unldenis** [comment]
What mc version are you using? I deduce one after 1.13 by reading the logs.

**Comment by zxcemelya** [comment]
1.16.5

**Comment by unldenis** [comment]
Try using the latest version (master-d5e092cc7a-1).
