### ISSUE TITLE
Update Method

### ISSUE THREAD

**Issue by CoetexDE** [unldenis/Hologram-Lib#4]
Is it possible to add method which update all lines in a Hologram?

**Comment by unldenis** [comment]
Do you intend to add lines?
If you want to change them you can already do it

**Comment by Lav1taDE** [comment]
I just mean a method with which you can update all lines without having to change anything on the hologram

**Comment by unldenis** [comment]
What is it supposed to do? Necessity of?

**Comment by GeorgeV220** [comment]
If I understand correctly he wants to reload the hologram without re-adding the lines. This is useful if you are using a placeholder and you want to be auto updated every 2 seconds for example or something like that.

**Comment by CoetexDE** [comment]
thank you very much, that's exactly what I mean

**Comment by GeorgeV220** [comment]
For now you can "hardcode" it and add a BukkitRunnable to run every 2 seconds and set the coresponding lines. Check the example on READ.ME
```java
    private void timingBlock(Hologram hologram) {
        new BukkitRunnable() {
            int j=1;
            @Override
            public void run() {
                if(j==materials.length) j=0;
                hologram.setLine(0, String.valueOf(j));
                hologram.setLine(3, new ItemStack(materials[j++]));
            }
        }
        .runTaskTimer(plugin, 30L, 30L);
    }
```
If you have the Hologram object you can set only the lines you want to update and nothing else.

an example is this:

```java
public void updatePlaceholders(Hologram hologram) {
        new BukkitRunnable() {
                hologram.setLine(0, placeholder /* it can be anything */);
        }
        .runTaskTimer(plugin, 0L, 40L);
}
```

**Comment by unldenis** [comment]
I had been thinking about changing something for a while, now I've done it!
Thanks to the latest version (1.2.5) you will be able to update the hologram whenever you want, as well as a better design for managing them.
Now you can conveniently use the AbstractLine#update method.

**Comment by unldenis** [comment]
I had been planning to do this for a while, however thanks to today's commits https://github.com/unldenis/Hologram-Lib/commits/master I was able to create a better design for managing them (1.2.5).
In 1.2.6 I added the AbstractLine#update() method, useful for the purpose of this PR.
The readMe example has been updated.

**Comment by CoetexDE** [comment]
Perfect

**Comment by CoetexDE** [comment]
Can you also update the NPCHologram Class in the NPC-Lib repo?

**Comment by CoetexDE** [comment]
Can you update the NPCHologram Class in the NPC-Lib repo?

**Comment by unldenis** [comment]
Now yes
https://github.com/unldenis/NPC-Lib/tree/hologramlib-integration
