### ISSUE TITLE
warn spam in console when changing world

### ISSUE THREAD

**Issue by SchweizerDev** [unldenis/Hologram-Lib#5]
Hi, i use the Hologram-Lib version 1.2.1. But its spam a error in console when somebody change the world. HydroGame is the overworld and HydroGame_nether the nether. I don't know why its spamming like this. By the way its only spamming, when a player, no matter who, is in the nether. 

I use the Hologram-Lib for my ChestShop system. when a ChestShop is created, it displays the item above the chest that the player is selling.
Here is a screen:
![hologram](https://user-images.githubusercontent.com/80473289/158329320-d6395627-1521-4119-9e00-8e03f4b97300.png)

Somebody has a idea?

**Comment by unldenis** [comment]
Fixed, if you encounter this error again please open another issue.

**Comment by SchweizerDev** [comment]
Thanks for your fast fix. Can you release a new version, that i can use it with maven? Or is it already pushed for maven usage?
