### ISSUE TITLE
Interaction with Hologram

### ISSUE THREAD

**Issue by CoetexDE** [unldenis/Hologram-Lib#9]
Is it possible to add a Event to interact with Holograms?

**Comment by unldenis** [comment]
I implemented the interaction with the holograms by creating listening to the left clicks of the players and creating the hitboxes for the desired hologram lines.
From version 1.2.7.

I keep this issue open to hear what you think and maybe improve the system that is currently synchronous.

**Comment by CoetexDE** [comment]
Cool, I'll test it soon.
